- packages/falcon-client/package.json
FIX
falcon-client dependencies
> fix: fixed client dependencies

- packages/falcon-client/package.json
- packages/falcon-client/src/buildTools/razzle/falconClientPlugin.js
> fixed building falcon client

- packages/falcon-client/package.json
- packages/falcon-client/src/buildTools/razzle/falconClientPlugin.js
Fix falcon client graphql loader
> Fix falcon client graphql loader

- .github/CONTRIBUTING.md
- README.md
Docs update for README.md and CONTRIBUTION.md. It fixes some typos and the quality of some sentences.
Has some typos. The doc can be improved.
Docs improved
-
-
> docs: Improved README.md and CONTRIBUTION.md, Fixed typos and improved sentences

- .travis.yml
- README.md
Bug fix and docs update.
Yarn is installed with npm, which should not be the case.
Yarn is installed according to the official docs.
No.
> ci: install Yarn properly

- renovate.json
> Setting Renovate "prConcurrentLimit" config

- packages/falcon-ecommerce-uikit/src/Breadcrumbs.tsx
- packages/falcon-magento2-api/src/index.js
- packages/falcon-magento2-api/src/index.test.js
Fixes #62 - urls in breadcrumbs are correctly rendered.
Urls in breadcrumbs were not prefixed with leading slash.
Leading slash has been added to urls of breadcrumbs items and last breadcrumb item is rendered as `Text` instead of `Link`.
No
> Fix breadcrumbs

- packages/falcon-errors/src/codes.js
- packages/falcon-magento2-api/src/Magento2ApiBase.js
throw a error when the admin token cant be found. probably the magento-api was not installed
> improved error handling on invallid admin token

- packages/falcon-client/src/clientApp/index.js
> Fixing broken re-export statements in example

- examples/shop-with-blog/client/src/App.js
- packages/falcon-ecommerce-uikit/src/Footer/Footer.tsx
- packages/falcon-ecommerce-uikit/src/Footer/FooterQuery.tsx
- packages/falcon-ecommerce-uikit/src/Footer/LanguageSwitcher.tsx
- packages/falcon-ecommerce-uikit/src/Footer/Newsletter.tsx
- packages/falcon-i18n/i18n/en/shop.json
Closes https://github.com/deity-io/falcon/issues/120
> ecommerce-uikit cleanup

- .gitlab-ci.yml
- .travis.yml
- README.md
Switching to GitLab CI
Closes #88
> Adding gitlab-ci config file

- packages/create-falcon-app/src/index.js
Adding extra check for directory
> Create-falcon-app fix (directory check)

- examples/shop-with-blog/client/src/pages/shop/Checkout/AddressSection.js
- examples/shop-with-blog/client/src/pages/shop/Checkout/Checkout.js
- examples/shop-with-blog/client/src/pages/shop/Checkout/CustomerSelector.js
- examples/shop-with-blog/client/src/pages/shop/Checkout/PaymentMethodSection.js
- examples/shop-with-blog/client/src/pages/shop/Checkout/ShippingMethodSection.js
- examples/shop-with-blog/client/src/pages/shop/components/AddressForm.js
This pull request fixes warnings about duplicates ids in address forms on checkout page.
> Fix ids in address forms on checkout page

- examples/shop-with-blog/client/src/theme.js
- packages/falcon-ecommerce-uikit/src/Header/Header.tsx
Updated theme colors and accessibility improvements
No
> theme changes and accessibility improvement

- packages/falcon-magento2-api/src/index.js
Fixes the way cart data is removed from the session (it was using old ref to the session).
> Fix error on order confirmation screen

- packages/falcon-client/package.json
- packages/falcon-dev-tools/falcon-i18n-webpack-plugin/package.json
- packages/falcon-ui/package.json
- yarn.lock
> Removing deprecated "types/deepmerge" package

- examples/shop-with-blog/client/src/pages/shop/Cart/index.js
- packages/falcon-ecommerce-uikit/src/MiniCart/MiniCart.tsx
- packages/falcon-i18n/i18n/en/translations.json
> fix minicart button translation

- packages/falcon-i18n/package.json
> fixing missing translation files

- examples/shop-with-blog/client/package.json
- packages/falcon-client/package.json
- packages/falcon-ecommerce-uikit/package.json
- packages/falcon-magento2-api/package.json
- packages/falcon-server-env/package.json
- packages/falcon-server/package.json
- packages/falcon-wordpress-api/package.json
- yarn.lock
> fixed  uikit dependencies

- examples/shop-with-blog/client/src/pages/shop/Checkout/PaymentMethodSection.js
- examples/shop-with-blog/client/src/pages/shop/Checkout/ShippingMethodSection.js
- packages/falcon-i18n/i18n/en/translations.json
- packages/falcon-i18n/i18n/nl/translations.json
Shows proper message on the checkout page when there are no shipping or payment methods available.
There's no information about missing shipping/payment methods atm.
> Show proper message when there are no shipping or payment options

- examples/shop-with-blog/client/src/pages/shop/Checkout/CustomerSelector.js
> Edit guest email on checkout

- examples/shop-with-blog/server/package.json
> Core-js fix

- packages/create-falcon-app/package.json
This will add keywords to npm-search
> Add Keywords to CFA package

- packages/falcon-ui/src/components/BackgroundImage.mdx
Docs update/fix
It says "BackDrop specific props" on BackgroundImage docs page
It says "BackgroundImage specific props" on BackgroundImage docs page
No
> Fixed componentName

- packages/falcon-client/src/index.js
> fix for hardcoded loadable-stats.json file path

- CHANGELOG.md
- UPGRADE.md
- package.json
- update changelog
- update upgrade guide
- change version in package.json
> Prepare v1.0-rc2

- packages/eject-ts/index.js
- packages/falcon-ecommerce-uikit/src/Forms/Field.tsx
> fix eject babel plugin resolution

- CHANGELOG.md
- packages/falcon-client/src/middlewares/routes/appHtmlMiddleware.js
- packages/falcon-client/src/middlewares/routes/index.js
fix: [359](https://github.com/deity-io/falcon/issues/359)
Google Tag manager is not being registered by app shell even when id is set on config file
> Fix for GoogleTagManager not being registered

- packages/falcon-ecommerce-uikit/src/Footer/Newsletter.tsx
- Bug fix
- #354 Inconsistent height of newsletter subscription button
- N/A
- No
- Fixed inconsistent height of newsletter input box with button, also verified changed in Desktop & Mobile version.
- Desktop: http://www.screencast.com/t/18NxZQFbT0
- Mobile: http://www.screencast.com/t/XwMHUnC6g
> Fixed alignment issue in newsletter box

- CHANGELOG.md
- examples/shop-with-blog/client/src/pages/shop/Checkout/AddressSection.js
- packages/falcon-magento2-api/src/endpoints.js
- packages/falcon-magento2-api/src/index.js
- packages/falcon-magento2-api/src/index.test.js
This pull request updates urls in falcon-magento2-api to be compatible with the latest changes mentioned in #367 and deity-io/falcon-magento2-development#84.
Closes #367
> Update magento2 api urls

- packages/falcon-magento2-api/src/index.js
- packages/falcon-server-env/src/models/ApiDataSource.ts
- packages/falcon-server/src/schemaDirectives/CacheDirective.js
> Cache context

- CHANGELOG.md
- packages/falcon-server/src/containers/BaseContainer.js
improves DX
not all errors (if any) are reported when extensions are loaded
all errors during loading extensions will be reported on the console
no
> Improved way of importing modules on falcon server

- packages/falcon-i18n/i18n/nl/translations.json
> Update Dutch translations

- packages/falcon-client/build-utils/webpack/config/create.js
- packages/falcon-client/build-utils/webpack/tools.js
- packages/falcon-client/src/bootstrap/configureServer.js
- packages/falcon-client/src/i18n/i18nServerFactory.js
- packages/falcon-client/src/middlewares/error500Middleware.js
- packages/falcon-client/src/middlewares/routes/apolloClientProvider.js
- packages/falcon-client/src/middlewares/routes/appHtmlMiddleware.js
- packages/falcon-client/src/middlewares/routes/appShellMiddleware.js
- packages/falcon-client/src/middlewares/routes/i18nextMiddleware.js
- packages/falcon-client/src/middlewares/routes/index.js
- packages/falcon-client/src/middlewares/routes/ssrMiddleware.js
- packages/falcon-client/src/server.js
- packages/falcon-client/src/service/ApolloClient.js
- packages/falcon-client/src/service/apolloStateToObject.js
- packages/falcon-client/test-utils/FalconClient.js
- packages/falcon-dev-tools/eslint-config-falcon/index.js
- packages/falcon-dev-tools/eslint-config-falcon/package.json
- packages/falcon-dev-tools/falcon-i18n-webpack-plugin/index.js
- packages/falcon-dev-tools/falcon-i18n-webpack-plugin/src/index.js
- packages/falcon-magento2-api/src/Magento2ApiBase.js
- packages/falcon-magento2-api/src/endpoints.js
- packages/falcon-magento2-api/src/index.js
- packages/falcon-server/src/containers/ApiContainer.js
- packages/falcon-server/src/containers/BaseContainer.js
- packages/falcon-server/src/containers/ExtensionContainer.js
- packages/falcon-server/src/index.js
- packages/falcon-server/src/resolvers/DynamicRouteResolver.js
- packages/falcon-server/src/schemaDirectives/GraphQLCacheDirective.js
- packages/falcon-wordpress-api/src/index.js
- yarn.lock
Adds consistent rules for jsdoc
No
> eslint Jsdoc plugin

- packages/falcon-client/package.json
- packages/falcon-client/src/middlewares/routes/appHtmlMiddleware.js
- packages/falcon-client/src/middlewares/routes/appShellMiddleware.js
- packages/falcon-client/src/middlewares/routes/assetsMiddleware.js
- packages/falcon-client/src/middlewares/routes/i18nextMiddleware.js
- packages/falcon-client/src/middlewares/routes/index.js
- packages/falcon-client/src/middlewares/routes/ssrMiddleware.js
- packages/falcon-client/src/middlewares/routes/webpackAssetsMiddleware.js
- yarn.lock
performance improvement
loadable component ChunkExtractor is created on each request
loadable component ChunkExtractor is not created on each request anymore
no
* `koa-i18next` is also removed
> Optimization of loadable components setup

- packages/falcon-client/bin/falcon-client.js
fix for a typo in import expression
`falcon-client` does not start
no
no
> fix for falcon-client startup

- examples/shop-with-blog/client/src/App.js
- package.json
- yarn.lock
- consistent across entire monorepo eslint configuration
NO
> Fix eslint

- packages/falcon-ecommerce-uikit/src/Checkout/TotalRow.tsx
- packages/falcon-ecommerce-uikit/src/Order/OrderQuery.tsx
- packages/falcon-magento2-api/src/Magento2ApiBase.js
- packages/falcon-magento2-api/src/index.js
- packages/falcon-shop-extension/src/schema.graphql
fix for wrongly displayed various prices on order pages 
No
> Fix order pages

- packages/falcon-magento2-api/src/index.js
> Fixing Customer endpoint

- packages/falcon-dev-tools/eslint-config-falcon/index.js
description for `@param` or `@returns` will be optional
NO
NO
> Optional @param/@returns description

- examples/shop-with-blog/client/src/pages/shop/Account/AddressBook/AddressBook.js
- packages/falcon-magento2-api/src/index.js
- packages/falcon-shop-data/src/Account/RequestPasswordResetMutation.tsx
- packages/falcon-shop-data/src/Account/ResetCustomerPasswordMutation.tsx
- packages/falcon-shop-data/src/Address/AddAddressMutation.tsx
- packages/falcon-shop-data/src/Address/AddressListQuery.tsx
- packages/falcon-shop-data/src/Address/AddressQuery.tsx
- packages/falcon-shop-data/src/Address/EditAddressMutation.tsx
- packages/falcon-shop-data/src/Customer/ChangePasswordMutation.tsx
- packages/falcon-shop-data/src/Customer/CustomerQuery.tsx
- packages/falcon-shop-data/src/Customer/CustomerWithAddressesQuery.tsx
- packages/falcon-shop-data/src/Customer/EditCustomerMutation.tsx
- packages/falcon-shop-data/src/Customer/IsAuthenticatedQuery.tsx
- packages/falcon-shop-data/src/Customer/index.ts
- packages/falcon-shop-data/src/Customer/types.ts
- packages/falcon-shop-data/src/types.ts
- packages/falcon-shop-extension/src/schema.graphql
- packages/falcon-shop-extension/src/types.ts
> Uikit fix partial typings

- packages/falcon-client/build-utils/webpack/config/create.js
- [x ] The commit message follows our guidelines
fix
> Fix for undefined PublicPath

- packages/falcon-client/src/service/ApolloClientWeb.js
- [x ] The commit message follows our guidelines
fix https://github.com/deity-io/falcon/issues/480
> Attempt to fix offline

- packages/falcon-client/build-utils/serviceWorker/workbox.js
- packages/falcon-client/build-utils/tools/index.js
- packages/falcon-client/package.json
- packages/falcon-dev-tools/falcon-scripts/package.json
- packages/falcon-dev-tools/falcon-scripts/src/build-cjs.js
- packages/falcon-dev-tools/normal-module-override-webpack-plugin/package.json
- yarn.lock
there was an issue with precaching `/app-shell` (especially in development mode) because of too large files which were taken into account to calculating hash.
> Fix appshell precache

- examples/shop-with-blog/client/src/pages/shop/Account/Orders/Order.js
Minor bug fix.
Some translations in "Account" section are missing or invalid (see #363).
Currently, the "Payment method" field has the correct value. I was unable to reproduce the first part of the issue regarding order status.
No.
**Other information**
WIP: since I was unable to reproduce the first part of #363, we should look into this to see if the issue persists.
> fix: invalid payment method (WIP)

- packages/falcon-dev-tools/eslint-config-falcon/index.js
- packages/falcon-ui/src/theme/utils.ts
Bug fix
falcon ui themes are merged correctly
falcon ui themes were not merged when there was an `undefined` or `null` property inside
NO
NO
> Fix theme merge

- UPGRADE.md
Apologies, I forgot to add upgrade notes
> Adding Upgrade notes for "Async cache calls" PR

- CHANGELOG.md
- UPGRADE.md
- examples/shop-with-blog/client/bootstrap.js
- examples/shop-with-blog/client/config/default.json
- examples/shop-with-blog/client/falcon-client.build.config.js
- examples/shop-with-blog/client/src/pages/shop/Cart/components/CartItem.js
- examples/shop-with-blog/client/src/pages/shop/Cart/components/CartSummary.js
- packages/falcon-client/build-utils/serviceWorker/index.js
- packages/falcon-client/src/bootstrap/configureServer.js
- packages/falcon-client/src/serviceWorker/sw.js
- packages/falcon-magento2-api/src/endpoints.js
Bugfix
After enabling full-page "cache" (via service-worker) - the proxied endpoints were left behind the cache by mistake.
All "proxied" endpoints that we handle on Falcon-Client must be processed without any cache calls in the browser. This PR defines a `blacklist` of routes that will be excluded from the generated `sw.js` file. Due to the nature of building `sw.js` file (mostly for production use) - this list of routes must be available inside of Falcon-Client application (to be able to build the required files using CI/CD), thus we cannot fetch this list dynamically …
> Changing "proxy-endpoints" flow

- packages/falcon-server-env/src/cache/Cache.ts
- packages/falcon-server-env/src/models/ApiDataSource.test.ts
- packages/falcon-server-env/src/models/ApiDataSource.ts
- packages/falcon-server-env/src/models/Extension.test.ts
- packages/falcon-wordpress-api/src/index.test.js
> Passing cache provider to HttpCache without a wrapper class

- .gitlab-ci.yml
- CHANGELOG.md
- UPGRADE.md
- examples/shop-with-blog/client/bootstrap.js
- examples/shop-with-blog/client/config/default.json
- examples/shop-with-blog/client/falcon-client.build.config.js
- examples/shop-with-blog/client/src/pages/shop/Cart/components/CartItem.js
- examples/shop-with-blog/client/src/pages/shop/Cart/components/CartSummary.js
- packages/falcon-client/build-utils/serviceWorker/index.js
- packages/falcon-client/src/bootstrap/configureServer.js
- packages/falcon-client/src/serviceWorker/sw.js
- packages/falcon-magento2-api/src/endpoints.js
- packages/falcon-magento2-api/src/index.js
- packages/falcon-server-env/src/cache/Cache.ts
- packages/falcon-server-env/src/models/ApiDataSource.test.ts
- packages/falcon-server-env/src/models/ApiDataSource.ts
- packages/falcon-server/src/containers/ApiContainer.ts
- packages/falcon-server/src/containers/ExtensionContainer.test.ts
- packages/falcon-server/src/containers/ExtensionContainer.ts
- packages/falcon-server/src/index.ts
- packages/falcon-server/src/schemaDirectives/GraphQLCacheDirective.ts
- packages/falcon-server/src/schemaDirectives/GraphQLCacheInvalidatorDirective.ts
- packages/falcon-wordpress-api/src/index.test.js
There are some eslint warnings left to fix (I'll do that)
> Uikit rework merge

- packages/falcon-client/build-utils/index.js
Bug fix
Small typo in log output
No
> Fix small typo in log output

- examples/shop-with-blog/client/src/pages/shop/CheckoutConfirmation.js
- packages/falcon-i18n/i18n/en/translations.json
- packages/falcon-magento2-api/src/index.js
Fix
checkout confirmation does not render correctly
it works again
No
No
> fix of LastOrder resolver

- packages/falcon-client/build-utils/serviceWorker/index.js
- packages/falcon-client/build-utils/tools/index.js
> Excluding sw.js from being cached by itself

- examples/shop-with-blog/client/src/pages/shop/Account/Orders/Order.js
Bug fix.
Payment method section shows shipping method instead (closes #363).
Fixed.
No.
> Fix: display payment method on order page

- examples/shop-with-blog/client/src/pages/shop/Category/Filters.js
Bug fix
There is a duplicate code block, these can be merged in the switch-case statement.
Same as before. But no duplicate code block.
No
> Merge duplicate 'price' case with default case

- CHANGELOG.md
- examples/shop-with-blog/client/package.json
- examples/shop-with-blog/server/package.json
1. Moved most of the dependencies from "dependencies" to "devDependencies" in `client/package.json` as `yarn install --production` should install only required packages to run in production mode, nothing more
2. Added `build:prod` step in `server/package.json` so it can be used in Dockerfiles if some additional work needs to be done before running FS in production mode
> Fix example client dependencies and add "build:prod" to the server

- CHANGELOG.md
- packages/falcon-i18n/src/I18n.tsx
improvement
it is now possible to get access to translation `t` function from hook 🚀 
```
import { useI18n } from '@deity/falcon-i18n';
const { t } = useI18n();
```
no
no
> Added useI18n hook

- CHANGELOG.md
- packages/falcon-server-env/src/models/EndpointManager.ts
- packages/falcon-server/src/containers/ComponentContainer.ts
- packages/falcon-server/src/containers/EndpointContainer.ts
- packages/falcon-server/src/index.ts
Improvement
When implementing endpoints for cache invalidation - there was no `cache` component exposed in the `EndpointManager` instance.
**Does this PR introduce a breaking change?**
No
> Improving data-sharing across Containers

- packages/falcon-ui/src/components/Button.tsx
Bug fix.
The current value of `arrow` is invalid CSS, so the fallback `pointer` (hand) cursor is shown when hovering over a disabled button.
The disabled button now shows the default cursor when hovered.
No.
> Fix cursor style on disabled button

- CHANGELOG.md
- packages/falcon-front-kit/src/SSR/InBrowserOnly.tsx
- packages/falcon-front-kit/src/SSR/index.ts
- packages/falcon-front-kit/src/index.ts
> Component which will render its children only in browser

- packages/falcon-ui-kit/src/Menu/MenuNavbar.tsx
> Fixed navbar children rendering

- packages/falcon-front-kit/src/Search/searchState.ts
Passing `{ pagination: { page: 1 } }` (only page number) leads to an error with `toString() of undefined` for `perPage` var.
> Separate checks for pagination in "searchStateToURL"

- packages/falcon-dev-tools/babel-preset-falcon-client/svgoConfig.js
> Fix for SVGO default config export

- packages/falcon-ui/src/theme/utils.ts
> fix for imports in falcon-ui

- examples/shop-with-blog/client/src/App.js
- packages/falcon-front-kit/src/DynamicRoute/SwitchDynamicUrl.tsx
> Fix for incorrectly handled NotFound via SwitchDynamicURL

- packages/falcon-ui-kit/src/helpers.ts
FIX
I am sorry for introducing this warning/bug/issue
> fix for not supported kebab-case

- examples/shop-with-blog/client/src/pages/shop/Checkout/Checkout.js
- packages/falcon-front-kit/src/Checkout/CheckoutContext.tsx
- packages/falcon-front-kit/src/Checkout/CheckoutProvider.tsx
- packages/falcon-front-kit/src/Checkout/CheckoutStep.ts
- packages/falcon-front-kit/src/Checkout/__tests__/CheckoutContext.test.tsx
improvement
checkout `step` is changed automatically when its `values` are updated
it is possible to configure default behavior, so checkout `step` can be updated via `stepForward()` method
> Optional "move forward" on Checkout

- packages/falcon-server-env/src/events.ts
- packages/falcon-server/src/containers/ApiContainer.ts
- packages/falcon-server/src/index.ts
- packages/falcon-server/src/middlewares/cacheInvalidatorMiddleware.ts
- packages/falcon-server/src/types.ts
> Adding event handler to invalidate cache tag(s)

- CHANGELOG.md
- examples/shop-with-blog/client/package.json
- examples/shop-with-blog/client/src/components/Header.js
- packages/falcon-shop-data/src/Cart/CartQuery.tsx
- yarn.lock
Fix
Loading invalid cart ID on SSR does not properly remove it from the cookie.
Loading Cart data is being done on the client-side only (handling new cookies properly).
No
> Fixing loading Cart on SSR

- packages/falcon-blog-data/src/Post/PostQuery.tsx
This branch adds the blog image to the post query so it's available on the post page.
> Add image to post page

- packages/falcon-wordpress-api/src/index.js
> Change the isEntityRedirect function to always return a bool

- CHANGELOG.md
- packages/falcon-front-kit/src/Routes/ProtectedRoute.tsx
the query string is not supported via `<ProtectedRoute  redirectTo=""`
the query string is supported
no
no
> Added support for query string in redirectTo path

- packages/falcon-shop-data/src/Order/OrderListQuery.tsx
Fix
Pagination is not working due to recent rework changes
Now it's being properly handled.
No
> Fixing OrderListQuery pagination

- packages/falcon-ui/src/components/Button.tsx
What are your thoughts on adding this back in? I know it can be ugly sometimes but is pretty useful for keyboard users.
**If you're happy with this suggestion I'll run through the PR checklist below.**
> Add default focus state

- packages/falcon-client/build-utils/paths.js
- packages/falcon-client/build-utils/webpack/config/create.js
> fixed babel config override
