deity-io/falcon

packages/falcon-client/src/index.js

Feature
The client server logs `started` when it's created.
The client server logs `Client ready at http://localhost:PORT` when it's created.
No
Just thought it might be worth having the url to the client server logged when the server is ready, I know it's mentioned in the docs but since the server side already does this I though it might be worth keeping it consistent and easier to remember.
| Before | After |
| --- | --- |
| …

feat: log client server url

---

packages/falcon-ui/src/components/Dropdown.tsx

Dropdown component doesn't render its children when it's closed - that way it doesn't affect the performance when there's a lot of items in the dropdown.

Do not render dropdown's items if the dropdown is closed

---

packages/falcon-magento2-api/src/index.js

Fixes logic for fetching product data and breadcrumbs when user is signed in.
Code uses wrong token when user is signed in so product data and breadcrumbs cannot be fetched.

Use correct token when fetching product data and breadcrumbs from new api

---

packages/falcon-magento2-api/src/Magento2ApiBase.js
packages/falcon-server/src/containers/ExtensionContainer.js
packages/falcon-wordpress-api/src/index.js

Fixes #341 - removed `defaultLocale` from api classes as we don't use that property anymore.

fix: remove defaultLocale from api classes as we don't use it anymore

---

examples/shop-with-blog/client/package.json
package.json
packages/falcon-client/build-utils/webpack/config/create.js
packages/falcon-client/package.json
packages/falcon-ecommerce-uikit/package.json
yarn.lock

fix: #357
I propose to totally remove `nodeExternals`, reasons:
- it works differently in and outside of monorepo
- I have hard times when trying to configure it to compile only `@deity` packages
- `falcon-client` compilation output is not a library, so every dependency could be compiled in output bundle
I see only one disadvantage of this solution:
- the compilation time could increase. I wrote "it could" as I do not notice.

Fix module override

---

packages/falcon-ecommerce-uikit/src/Checkout/CheckoutLogic.tsx
packages/falcon-magento2-api/src/index.js

There are 2 changes:
1. Removed workaround (introduced in commit 9b16c43) that was making sure that CheckoutLogic does not throw an error when ApolloClient calls success callback twice. New version of ApolloClient does not have that problem so the workaround is not needed anymore
2. Fixed name of id attribute in magento2 api - it's called now `customer_address_id` as magento accepts that one (instead of `id` when sending address from address book)
See #399.
The problem is removed - user can now correctly use address from his address book.

Fix checkout issue

---

packages/falcon-magento2-api/src/index.js

`extension_attributes` have been removed from sign-up request as that parameter is not supported anymore by this endpoint (we now use separate api for cart merging which is automatically executed when user signs in).
Api client sends `extension_attributes` and it causes error in Magento
Parameter has been removed - sign up works correctly

Fix signup for magento 2.2

---

examples/shop-with-blog/client/src/pages/shop/Category/Category.js
packages/falcon-ecommerce-uikit/src/Category/CategoryLayout.tsx

Bug Fix
when our backend does not return Filters for Category (which is rather rare) we display  blank filter aside next to 
when there are no filters then we expand ProductList into entire available width (no more blank filter aside)
No

CategoryLayout with noFilters variant

---

packages/falcon-magento2-api/src/index.js
packages/falcon-magento2-api/src/index.test.js

Use `image` property for `thumbnail` field on listing pages when there are no `extension_attributes` passed.
`thumbnail` is not set when `extension_attributes` field is not passed
As above.
No
-

Product thumbnail fix

---

packages/falcon-ecommerce-uikit/src/MiniCart/MiniCart.tsx

It turned out that we use NumberInput as uncontrolled while it should be controlled in that case. This pr changes the behavior to correct one. (fixes #502)

Fix product count in MiniCart

---

packages/falcon-client/docs/ANALYTICS.md

Adds typename for GraphQL
```
Missing field __typename in {
"trackerID": "UA-XXXXXXXX"
}
```
Falcon gives this error in the client when this line doesn't exist. Apollo Client needs it.
No error, track pageviews correct
No

Add typename for Apollo Client

---

.gitlab-ci.yml
.travis.yml
CHANGELOG.md
packages/falcon-client/package.json
packages/falcon-server/src/containers/BaseContainer.js
yarn.lock

According to the "Long Term Support (LTS) schedule" - Node 11 is not gonna last long.
Fixes #536

Node 12 compatibility

---

CHANGELOG.md
packages/falcon-server-env/src/models/Extension.ts

Improvement. Getting rid of partially working RegExp patterns, parsing partial schemas using native `graphql` parse method without making such schemas "executable".
Currently, it only works in certain conditions (multiline directives not fully supported by these RegExp patterns).
Fully featured support of GraphQL syntax without a need to support RegExp patterns.
Fully backward compatible, no changes required (it's an internal change)
According to trace logs - improved the speed of parsing the root fields (about 2 times faster now).

Improving the way how Falcon extracts root fields from partial extension GQL schemas

---

packages/falcon-server-env/src/cache/Cache.ts

Bug fix
When using Redis/Memcached as a cache backend and setting value without a TTL option - Apollo forces `300` seconds (5 min) TTL by default (meaning - there's no way to set a cached value without an expiration):
- https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-cache-redis/src/RedisCache.ts#L8
- https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-cache-memcached/src/index.ts#L9
Setting 1 hour TTL for cache tags.
**Does this PR introduce a breaking change? (What changes might users need to make in their …

Adding TTL for cache tags

---

CHANGELOG.md
packages/falcon-magento2-api/src/index.js
packages/falcon-server-env/src/cache/Cache.ts
packages/falcon-server-env/src/models/ApiDataSource.test.ts
packages/falcon-server-env/src/models/ApiDataSource.ts
packages/falcon-server/src/containers/ApiContainer.js
packages/falcon-server/src/containers/ExtensionContainer.js
packages/falcon-server/src/containers/ExtensionContainer.test.js
packages/falcon-server/src/index.js
packages/falcon-server/src/schemaDirectives/GraphQLCacheDirective.js
packages/falcon-server/src/schemaDirectives/GraphQLCacheInvalidatorDirective.js

As a part of the investigations to improve the Cache performance in Falcon-Server, there was an issue found with `addResolveFunctionsToSchema` calls during the runtime.
Initially, the issue was causing a problem with the `trace` plugin that hasn't been noticed for a long time (in this case - `magento2-api` package was adding its own additional `breadcrumbs` resolver during the runtime to handle `breadcrumbs` part properly - and therefore overwriting the whole `resolve` function for `breadcrumbs` field that was previously wrapped by the `trace` plugin and other directives):
After this fix - the "tracing" panel looks correct (`breadcrumbs` section is in place):
This find helped us to solve a problem with cache `get` calls (in combination with `set/get` trick in our Cache directives - it led …

Cache async calls

---

CHANGELOG.md
packages/falcon-server/schema.graphql
packages/falcon-server/src/graphqlUtils/index.ts
packages/falcon-server/src/schemaDirectives/GraphQLCacheDirective.test.ts
packages/falcon-server/src/schemaDirectives/GraphQLCacheInvalidatorDirective.test.ts
packages/falcon-shop-extension/schema.graphql

Yes. Falcon won't be checking for `ID` field types anymore, but instead, it will be checking for `@cacheId`-marked fields within the same Type.
Fixes #587

Introducing `@cacheId` directive

---

examples/shop-with-blog/client/package.json
packages/falcon-client/package.json
packages/falcon-data/package.json
packages/falcon-front-kit/package.json
yarn.lock

This PR fixes issue with yarn installing two versions of @apollo/react-common and @apollo/react-components (it was installing `3.1.1` because our packages required that version and `3.1.2` because apollo packages have `^3.1.1` specified)

fix apollo versions so yarn doesn't install 2 versions of some packages

---

.github/workflows/main.yml
codecov.yml
package.json
yarn.lock

Brings Codecov reports back.
Fixes #635 (Using `codecov-action` on Github Actions takes a lot more time than simply running `yarn coverage` command inside of the project - I decided not to use it)

Adding Codecov pipeline step

---

CHANGELOG.md
packages/falcon-client/build-utils/webpack/config/create.js
packages/falcon-dev-tools/babel-preset-falcon-client/index.js
packages/falcon-dev-tools/babel-preset-falcon-client/package.json
packages/falcon-dev-tools/babel-preset-falcon-client/svgoConfig.js
yarn.lock

when `.svg` files will be `import`ed or `require`ed then it will be converted (via `babel`) into react component and rendered inline 
moreover `.svg` files will be processed via `svgo` in order to optimize them
fix: https://github.com/deity-io/falcon/issues/605

Inlining SVG files by default

---

packages/falcon-front-kit/src/Search/index.ts
packages/falcon-front-kit/src/Search/useSearchContext.ts
packages/falcon-ui-kit/package.json
yarn.lock

- Re-exporting `SearchContext` to enable calling `useContext(SearchContext)`
- Updating "react-lazyload" dependency to fix the image loading

Enabling falcon-front-kit to export SearchContext + dependency update

---

.github/workflows/main.yml
.gitlab-ci.yml
examples/shop-with-blog/client/package.json
examples/shop-with-blog/server/package.json
package.json
packages/create-falcon-app/package.json

This PR raises the "required minimal node version" check from 8.10 to 10.15 (because `8.x`reaches the end-of-life within a couple of days).
The reason for `10.15` - it was released about a year ago, so there's a higher chance that developers would have it installed on their local machines, hence we would give them less stress during the upgrade.

Dropping Node 8 support

---

CHANGELOG.md
examples/shop-with-blog/client/src/pages/shop/Cart/components/CartSummary.js
packages/falcon-magento2-api/src/index.ts
packages/falcon-server/schema.graphql
packages/falcon-server/src/index.ts
packages/falcon-shop-data/src/Cart/CancelCouponMutation.tsx
packages/falcon-shop-data/src/Cart/CartQuery.tsx
packages/falcon-shop-extension/schema.graphql
packages/falcon-shop-extension/src/types.ts

Feature. Having a `couponCode` string field on Cart/Order is not enough for advanced templates.
This PR introduces `Coupon` type for Shop Extension.
This PR allows using multiple coupon codes for the cart (if backend supports it, like WooCommerce). Allows removing a specified coupon using its code.
Yes

Improving Coupon type across the schema

---

CHANGELOG.md
examples/shop-with-blog/client/src/pages/shop/Category/Category.js
examples/shop-with-blog/client/src/pages/shop/Sidebar/SidebarContents.js
packages/falcon-ui-kit/src/Layouts/SidebarLayout.tsx
packages/falcon-ui-kit/src/Sidebar/Sidebar.tsx

Small feature change.
Sidebar close icon position is hardcoded in ui-kit's `Sidebar`.
Sidebar icon is positioned next to title in `SidebarLayout`. If a user wants to use a different layout, they only need to override `SidebarLayout`.
Wherever the `SidebarLayout` component is used, it should be passed an `onClose` prop to make the close button work.

Sidebar close icon

---

CHANGELOG.md
packages/falcon-server-env/src/cache/Cache.ts

Bugfix
When the Cache getter was called with `fetchData` setter callback option - this callback may throw an error and internal "callback queue" wasn't cleared after that (so the app was stuck) 
Using `try/finally` to remove the failing cache call from the queue in any case.
No
- Run both Falcon apps (from the example folder)
- Load the application normally
- Disable network connections for Falcon-Server (like disabling the wifi)
- Visit the non-cached page - **See the error**
- Enable …

Fixing cache queue error handling
